version: '3'
services:
  mysql:
    container_name: 'mysql'
    image: mysql
    environment:
      MYSQL_DATABASE: testsdb
      MYSQL_USER: szymek
      MYSQL_PASSWORD: '!hoax?123a'
    ports:
    - "3306:3306"
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

